task:
  timeout_in: 5m
  container:
    image: gcc:latest
  env:
    ASAN_OPTIONS: detect_leaks=0
  build_script:
    - sh build.sh
  test_build_bob_with_bob_script:
    - $(realpath sh-bin/bob) build
  test_run_bob_with_bob_script:
    - rm -rf .bob
    - $(realpath sh-bin/bob) run build
  test_install_bob_script:
    - rm -rf .bob
    - $(realpath sh-bin/bob) install
  test_run_installed_bob_script:
    - rm -rf .bob
    - bob build
  amd64_artifacts:
    path: ".bob/prefix/bin/bob"

task:
  timeout_in: 5m
  arm_container:
    image: gcc:latest
  env:
    ASAN_OPTIONS: detect_leaks=0
  build_script:
    - sh build.sh
  test_build_bob_with_bob_script:
    - $(realpath sh-bin/bob) build
  test_run_bob_with_bob_script:
    - rm -rf .bob
    - $(realpath sh-bin/bob) run build
  test_install_bob_script:
    - rm -rf .bob
    - $(realpath sh-bin/bob) install
  test_run_installed_bob_script:
    - rm -rf .bob
    - bob build
  arm64_artifacts:
    path: ".bob/prefix/bin/bob"
