task:
  timeout_in: 5m
  container:
    image: gcc:latest
  build_script:
    - apt install -y lsof
    - sh build.sh
  test_script:
    - CLICOLOR_FORCE= $(realpath sh-bin/bob) test install
  amd64_artifacts:
    path: "bin/bob"

task:
  timeout_in: 5m
  arm_container:
    image: gcc:latest
  build_script:
    - apt install -y lsof
    - sh build.sh
  test_script:
    - CLICOLOR_FORCE= $(realpath sh-bin/bob) test install
  arm64_artifacts:
    path: "bin/bob"
