task:
  name: Test Bob with GCC on Linux (amd64)
  timeout_in: 5m
  container:
    image: gcc:latest
  bootstrap_script:
    - sh bootstrap.sh
  tests_script:
    - sh tests.sh
  amd64_artifacts:
    path: ".bob/prefix/bin/bob"

task:
  name: Test Bob with GCC on Linux (arm64)
  timeout_in: 5m
  arm_container:
    image: gcc:latest
  bootstrap_script:
    - sh bootstrap.sh
  tests_script:
    - sh tests.sh
  arm64_artifacts:
    path: ".bob/prefix/bin/bob"

compute_engine_instance:
  platform: freebsd
  image_project: freebsd-org-cloud-dev
  image: freebsd-13-2-release-amd64
  cpu: 2
  memory: 4G

task:
  name: Test Bob with Clang on FreeBSD (x86_64)
  timeout_in: 30m
  bootstrap_script:
    - sh bootstrap.sh
  tests_script:
    - sh tests.sh
  amd64_artifacts:
    path: ".bob/prefix/bin/bob"
