// SPDX-License-Identifier: MIT
// Copyright (c) 2024-2026 Aymeric Wibo

/*
 * Cookies!
 *
 * Bob makes use of two types of cookies:
 *
 * - File placeholder cookies, which are what this API covers, and are represented by strings.
 * - Value placeholder cookies, which are a little more ad-hoc, but an example can be found in 'PkgConfigCookie()'.
 *
 * Cookies are intermediary files placed under '.bob/<target>/bob'.
 * They are generated by certain functions in the Bob build script so they can be used before the relevant build step runs.
 * For example, the compile -> link flow looks like this:
 *
 * - We start parsing 'build.fl'.
 * - A call to 'Cc().compile()' returns a cookie to the compiled file. This file does not yet exist, but a build step to compile this is added.
 * - A call to 'Linker().link()' takes in the previously generated cookie. The file pointed to by the cookie does not yet exist, but a build step to link this is added.
 * - Now we've finished parsing 'build.fl', we run the build steps.
 * - The compile build step actually creates the cookie file.
 * - The link build step can then just use that cookie file directly.
 *
 *               .---. .---.
 *              :     : o   :    me want cookie!
 *          _..-:   o :     :-.._    /
 *      .-''  '  `---' `---' "   ``-.
 *    .'   "   '  "  .    "  . '  "  `.
 *   :   '.---.,,.,...,.,.,.,..---.  ' ;
 *   `. " `.                     .' " .'
 *    `.  '`.                   .' ' .'
 *     `.    `-._           _.-' "  .'  .----.
 *       `. "    '"--...--"'  . ' .'  .'  o   `.
 *       .'`-._'    " .     " _.-'`. :       o  :
 * jgs .'      ```--.....--'''    ' `:_ o       :
 *   .'    "     '         "     "   ; `.;";";";'
 *  ;         '       "       '     . ; .' ; ; ;
 * ;     '         '       '   "    .'      .-'
 * '  "     "   '      "           "    _.-'
 */

#pragma once

#include <pthread.h>
#include <stdbool.h>

/**
 * Generate a cookie path for a given source path and extension.
 *
 * @param path Source file path (does not need to be NUL-terminated; 'path_size' bytes are used).
 * @param path_size Length of 'path'.
 * @param ext Extension for the cookie file (e.g. "o" for object files).
 * @return Heap-allocated cookie path; caller must free.
 */
char* gen_cookie(char* path, size_t path_size, char const* ext);

/**
 * Record that a cookie has been built in this session.
 *
 * This function is thread-safe.
 *
 * @param cookie Cookie path as returned by {@link gen_cookie}.
 */
void add_built_cookie(char* cookie);

/**
 * Check whether a cookie has already been built in this session.
 *
 * Used to e.g. see if a dependant file has needed to be rebuilt; if when trying to link a program we see that a static library has been rebuilt and thus {@link add_built_cookie} had previously been called with it, then we know we have to re-link.
 * Otherwise, all else being the same, we might not need to re-link.
 * This function is thread-safe.
 *
 * @param cookie Cookie path to look up (not necessarily NUL-terminated; 'len' bytes are compared).
 * @param len Length of 'cookie'.
 * @return True if the cookie was previously added via {@link add_built_cookie}, false otherwise.
 */
bool has_built_cookie(char* cookie, size_t len);
