name: Linting and extra checks

on: [push, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up compiler
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64
      - name: Install intercept-build
        run: sudo apt install clang-tools
      - name: Get all source files
        run: echo "SRC=$(find src -name "*.[ch]" -print0 -o -path src/flamingo -prune -type f | xargs -0 echo)" >> $GITHUB_ENV
      - name: Build (with LSP output)
        run: intercept-build-18 sh bootstrap.sh
      - name: Run clang-tidy
        run: clang-tidy $SRC
      - name: Make sure 'mkdir_wrapped' is used everywhere (except for once for 'fsutils.c')
        run: |
          if [ $(cat $SRC | grep "[^\"]mkdir(" | wc -l) -gt 1 ]; then
            echo "Error: 'mkdir' is used in multiple places. Use 'mkdir_wrapped' instead."
            exit 1
          fi
      - name: Make sure 'realerpath' is used everywhere (except for once for 'fsutils.c')
        run: |
          if [ $(cat $SRC | grep "[^\"]realpath(" | wc -l) -gt 1 ]; then
            echo "Error: 'realpath' is used in multiple places. Use 'realerpath' instead."
            exit 1
          fi
      - name: Make sure 'malloc_c'/'calloc_c'/'realloc_c' are used everywhere (except for once in 'alloc.h')
        run: |
          for fn in malloc calloc realloc; do
            if [ $(cat $SRC | grep "[^\"]${fn}(" | wc -l) -gt 1 ]; then
              echo "Error: '${fn}' is used outside of 'alloc.h'. Use '${fn}_c' instead."
              exit 1
            fi
          done
      - name: Make sure 'strdup_c'/'strndup_c' are used everywhere (except for once in 'alloc.h')
        run: |
          for fn in strdup strndup; do
            if [ $(cat $SRC | grep "[^\"]${fn}(" | wc -l) -gt 1 ]; then
              echo "Error: '${fn}' is used outside of 'alloc.h'. Use '${fn}_c' instead."
              exit 1
            fi
          done
      - name: Make sure 'asprintf_c'/'vasprintf_c' are used everywhere (except for once in 'alloc.h')
        run: |
          if [ $(cat $SRC | grep "[^v]asprintf(" | wc -l) -gt 0 ]; then
            echo "Error: 'asprintf' is used outside of 'alloc.h'. Use 'asprintf_c' instead."
            exit 1
          fi
          if [ $(cat $SRC | grep "[^\"]vasprintf(" | wc -l) -gt 1 ]; then
            echo "Error: 'vasprintf' is used outside of 'alloc.h'. Use 'vasprintf_c' instead."
            exit 1
          fi
      - name: Make sure raw booleans aren't used as arguments to 'cmd_set_redirect()'
        run: |
          if [ "$(cat $SRC | grep -E "cmd_set_redirect.*\b(true|false\b)")" != "" ]; then
            echo "Error: 'cmd_set_redirect()' is called with raw booleans. Use 'CMD_{NO_,}{FORCE_,}REDIRECT' instead."
            exit 1
          fi
      - name: Set up tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 5
        with:
          limit-access-to-actor: true
          detached: true
